name = "ChemistryQuantitativeAnalysis"
uuid = "3ed48883-6809-43ec-b77a-d23b0650d8c4"
authors = ["Yu-Fong Peng <sciphypar@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
CSV = "0.10"
Dictionaries = "0.3"
GLM = "1.9"
ThreadsX = "0.1"
Tables = "1"
TypedTables = "1.4"
julia = "1.9"
