[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gtk4 = "9db2cae5-386f-4011-9d63-a5602296539b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
CSV = "0.10"
GLM = "1.9"
GLMakie = "0.8"
Plotly = "0.4"
PrettyTables = "2.2"
TypedTables = "1.4"
julia = "1.10"